services:
  backend_service:
    build: .
    image: kholmumin/django_backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres_service

  postgres_service:
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - 5437:${PG_PORT}
    volumes:
      - drf_p21_pg_data:/var/lib/postgresql/data

volumes:
  drf_p21_pg_data:
