# Generated by Django 5.0.7 on 2024-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/"),
        ),
    ]
